Update README.md
NHSDigital/mps_diagnostics pull request #5
Opened 2024-01-17 14:44 UTC by JonathanLaidler

Added environment details to the readme

2024-01-17 14:47 UTC, amaiaita approved these changes

2024-01-17 16:38 UTC, amaiaita requested changes

2024-01-17 16:38 UTC, amaiaita commented on MPSD flow diagram.png
- some color coding would be great for me visually - but not an absolute necessity. 
- The three dots at the bottom right dont feel fully descriptive to me, do they mean there could be more datasets there? 
- do the different shapes of boxes mean different things? if so, add a label!

2024-01-22 17:07 UTC, GiuliaMantovani1 approved these changes

2024-01-24 10:13 UTC, amaiaita approved these changes

2024-01-24 10:14 UTC, merged